# Generated by Django 3.2.3 on 2022-05-10 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220509_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='curtidas',
        ),
        migrations.AddField(
            model_name='post',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
